""" Constants module.
"""

PUBLIC_IDENTITY = 0
SECRET_IDENTITY = 1
NO_DUAL_IDENTITY = 2
KNOWN_AUTHORITIES_IDENTITY = 3
UNKNOWN_IDENTITY = 4

MALE_GENDER = 0
FEMALE_GENDER = 1
AGENDER_GENDER = 2
UNKNOWN_GENDER = 3
